### ISSUE TITLE
Board update loopt achter nadat de tegenstander 2x aan de beurt is geweest.

### ISSUE THREAD

**Issue by riboyama** [HanzehogeschoolSICT/Project-Othello#1]
De GUI loopt 1 stap achter met verversen nadat de tegenstander >= 2 keer aan de beurt is geweest.

**Comment by GeorgGroenendaal** [comment]
Lijkt erop dat getNewMove helemaal niet meer aangeroepen wordt. Komt overigens niet met twee menselijke spelers
